# Generated by Django 6.1 on 2026-09-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=10)),
                ('price_per_gallon', models.FloatField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
            options={
                'indexes': [models.Index(fields=['lat', 'lng'], name='fueloptimiz_lat_0d2a12_idx')],
            },
        ),
    ]
